name: Uthenga
version: '0.1.1.0'
category: Devops
author: Arek Czarnik
maintainer: arekczarnik@gmail.com
copyright: 2017 Arek Czarnik
license: BSD3
github: ArekCzarnik/Uthenga
extra-source-files:
- README.md
dependencies:
- bytestring
- text
library:
  source-dirs: src
  exposed-modules:
  - Database.Disque
  - Database.MockDisque
  dependencies:
  - base >=4.7 && <5
  - transformers
  - aeson
  - hedis
executables:
  uthenga:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - scotty
    - hedis
    - aeson
    - string-conversions
    - wai
    - warp
    - wai-extra
    - Uthenga
tests:
  uthenga-test:
    main: Spec.hs
    source-dirs: test app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - scotty
    - hedis
    - aeson
    - string-conversions
    - wai
    - warp
    - wai-extra
    - Uthenga
    - hspec-wai
    - hspec
    - hspec-wai-json
