name: Uthenga
version: '0.1.1.0'
category: Devops
author: Arek Czarnik
maintainer: arekczarnik@gmail.com
copyright: 2017 Arek Czarnik
license: BSD3
github: ArekCzarnik/Uthenga
extra-source-files:
- README.md
dependencies:
- bytestring
- text
library:
  source-dirs: src
  exposed-modules:
  - Database.Disque
  - Application
  dependencies:
    - base
    - scotty
    - hedis
    - aeson
    - string-conversions
    - io-streams
    - wai
    - warp
    - wai-extra
    - http-types
    - mysql-haskell
executables:
  uthenga:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - scotty
    - hedis
    - aeson
    - string-conversions
    - io-streams
    - wai
    - warp
    - wai-extra
    - http-types
    - mysql-haskell
tests:
  uthenga-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -Wall
    dependencies:
    - base
    - scotty
    - hedis
    - aeson
    - string-conversions
    - wai
    - warp
    - wai-extra
    - Uthenga
    - hspec-wai
    - hspec
    - mysql-haskell
    - test-fixture
    - hspec-discover
    - hspec-wai-json
    - Uthenga
