version: 2
jobs:
  build:
    working_directory: ~/uthenga
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update && apt-get -y install curl && apt-get -y install netbase && apt-get -y install xz-utils && apt-get -y install build-essential && apt-get -y install libgmp3-dev
      - run: curl -L https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-linux-x86_64.tar.gz | tar zx -C /tmp
      - run: mv /tmp/stack-1.4.0-linux-x86_64/stack .
      - run: ./stack setup
      - run: ./stack build
      - run: ./stack test