version: 2
jobs:
  build:
    working_directory: ~/uthenga
    docker:
      - image: arekczarnik/docker-circleci-haskell
    steps:
      - checkout
      - run: ./stack setup
      - run: ./stack build
      - run: ./stack test