version: 2
jobs:
  build:
    working_directory: ~/uthenga
    docker:
      - image: arekczarnik/docker-circleci-haskell
      - image: mariadb:latest
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: uthenga
      - image: richnorth/disque:latest
    steps:
      - checkout
      - run: stack build --fast
      - run: stack test --no-terminal --coverage
      - run: stack exec -- shc --repo-token=$COVERALLS_REPO_TOKEN Uthenga uthenga-test