version: 2
jobs:
  build:
    working_directory: ~/uthenga
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: ls -la
      - run: wget -L https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-linux-x86_64.tar.gz
      - run: sudo mv /tmp/stack-1.4.0-linux-x86_64/stack /usr/bin
      - run: stack setup
      - run: stack build
      - run: stack test